//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Resourses.Views.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Store.Resourses.Views.Admin.AdminStrings", typeof(AdminStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new category.
        /// </summary>
        public static string add_category {
            get {
                return ResourceManager.GetString("add_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add customer.
        /// </summary>
        public static string add_customer {
            get {
                return ResourceManager.GetString("add_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new product.
        /// </summary>
        public static string add_product {
            get {
                return ResourceManager.GetString("add_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add shipper.
        /// </summary>
        public static string add_shipper {
            get {
                return ResourceManager.GetString("add_shipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add supplier.
        /// </summary>
        public static string add_supplier {
            get {
                return ResourceManager.GetString("add_supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new user.
        /// </summary>
        public static string add_user {
            get {
                return ResourceManager.GetString("add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin : Edit.
        /// </summary>
        public static string Admin_edit {
            get {
                return ResourceManager.GetString("Admin_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All products.
        /// </summary>
        public static string All_products {
            get {
                return ResourceManager.GetString("All_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string Create_New {
            get {
                return ResourceManager.GetString("Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new product.
        /// </summary>
        public static string create_new_product {
            get {
                return ResourceManager.GetString("create_new_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string customers {
            get {
                return ResourceManager.GetString("customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category.
        /// </summary>
        public static string edit_category {
            get {
                return ResourceManager.GetString("edit_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit customer.
        /// </summary>
        public static string edit_customer {
            get {
                return ResourceManager.GetString("edit_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit existing products.
        /// </summary>
        public static string edit_existing_products {
            get {
                return ResourceManager.GetString("edit_existing_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit product.
        /// </summary>
        public static string edit_product {
            get {
                return ResourceManager.GetString("edit_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit shipper.
        /// </summary>
        public static string edit_shipper {
            get {
                return ResourceManager.GetString("edit_shipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit supplier.
        /// </summary>
        public static string edit_supplier {
            get {
                return ResourceManager.GetString("edit_supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string edit_user {
            get {
                return ResourceManager.GetString("edit_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image error.
        /// </summary>
        public static string image_error {
            get {
                return ResourceManager.GetString("image_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove category.
        /// </summary>
        public static string remove_category {
            get {
                return ResourceManager.GetString("remove_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove customer.
        /// </summary>
        public static string remove_customer {
            get {
                return ResourceManager.GetString("remove_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove product.
        /// </summary>
        public static string remove_product {
            get {
                return ResourceManager.GetString("remove_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove shipper.
        /// </summary>
        public static string remove_shipper {
            get {
                return ResourceManager.GetString("remove_shipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove supplier.
        /// </summary>
        public static string remove_supplier {
            get {
                return ResourceManager.GetString("remove_supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user.
        /// </summary>
        public static string remove_user {
            get {
                return ResourceManager.GetString("remove_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles administration.
        /// </summary>
        public static string roles_administration {
            get {
                return ResourceManager.GetString("roles_administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shippers.
        /// </summary>
        public static string shippers {
            get {
                return ResourceManager.GetString("shippers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string suppliers {
            get {
                return ResourceManager.GetString("suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users list.
        /// </summary>
        public static string users_list {
            get {
                return ResourceManager.GetString("users_list", resourceCulture);
            }
        }
    }
}
