//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Resourses.Product {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Store.Resourses.Product.ProductStrings", typeof(ProductStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select category.
        /// </summary>
        public static string category_validation_error_message {
            get {
                return ResourceManager.GetString("category_validation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter description for product.
        /// </summary>
        public static string description_validation_error_message {
            get {
                return ResourceManager.GetString("description_validation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued.
        /// </summary>
        public static string discontinued {
            get {
                return ResourceManager.GetString("discontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct price.
        /// </summary>
        public static string price_validation_error_message {
            get {
                return ResourceManager.GetString("price_validation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string product_description {
            get {
                return ResourceManager.GetString("product_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product list.
        /// </summary>
        public static string product_list {
            get {
                return ResourceManager.GetString("product_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string product_name {
            get {
                return ResourceManager.GetString("product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid product name.
        /// </summary>
        public static string product_name_validation_error_message {
            get {
                return ResourceManager.GetString("product_name_validation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity per unit.
        /// </summary>
        public static string quantity_per_unit {
            get {
                return ResourceManager.GetString("quantity_per_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct quantity per unit.
        /// </summary>
        public static string quantity_per_unit_validation_error_message {
            get {
                return ResourceManager.GetString("quantity_per_unit_validation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder level.
        /// </summary>
        public static string reorder_level {
            get {
                return ResourceManager.GetString("reorder_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct quantity reorder level.
        /// </summary>
        public static string reorder_level_validation_error_message {
            get {
                return ResourceManager.GetString("reorder_level_validation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string supplier {
            get {
                return ResourceManager.GetString("supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string unit_price {
            get {
                return ResourceManager.GetString("unit_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units in stock.
        /// </summary>
        public static string units_in_stock {
            get {
                return ResourceManager.GetString("units_in_stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter quantity of products in stock.
        /// </summary>
        public static string units_in_stock_validation_error_message {
            get {
                return ResourceManager.GetString("units_in_stock_validation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units on order.
        /// </summary>
        public static string units_on_order {
            get {
                return ResourceManager.GetString("units_on_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid value of units on order.
        /// </summary>
        public static string units_on_order_validation_error_message {
            get {
                return ResourceManager.GetString("units_on_order_validation_error_message", resourceCulture);
            }
        }
    }
}
