//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Resourses.Registration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegistrationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistrationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Store.Resourses.Registration.RegistrationStrings", typeof(RegistrationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account information.
        /// </summary>
        public static string Account_Information {
            get {
                return ResourceManager.GetString("Account_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete registration ?.
        /// </summary>
        public static string Complete_registration {
            get {
                return ResourceManager.GetString("Complete_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password correctly.
        /// </summary>
        public static string Confirm_password_not_equal {
            get {
                return ResourceManager.GetString("Confirm_password_not_equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password required and must be equal to password field.
        /// </summary>
        public static string Confirm_Password_validation_error_message {
            get {
                return ResourceManager.GetString("Confirm_Password_validation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation errors exist.
        /// </summary>
        public static string CreatingAccontErrorsExist {
            get {
                return ResourceManager.GetString("CreatingAccontErrorsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer detail register info.
        /// </summary>
        public static string Customer_detail_register_info {
            get {
                return ResourceManager.GetString("Customer_detail_register_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer with this id already exists.
        /// </summary>
        public static string customer_id_already_exists {
            get {
                return ResourceManager.GetString("customer_id_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer main register  info.
        /// </summary>
        public static string Customer_main_register_customer_info {
            get {
                return ResourceManager.GetString("Customer_main_register_customer_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer detail registration.
        /// </summary>
        public static string CustomerDetails {
            get {
                return ResourceManager.GetString("CustomerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer registration.
        /// </summary>
        public static string CustomerRegistration {
            get {
                return ResourceManager.GetString("CustomerRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be not less then 2 symbols.
        /// </summary>
        public static string Password_lenght_error_message {
            get {
                return ResourceManager.GetString("Password_lenght_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration сompleted.
        /// </summary>
        public static string RegistrationCompleted {
            get {
                return ResourceManager.GetString("RegistrationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email already exists.
        /// </summary>
        public static string user_emai_already_exists {
            get {
                return ResourceManager.GetString("user_emai_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration of user.
        /// </summary>
        public static string UserRegistration {
            get {
                return ResourceManager.GetString("UserRegistration", resourceCulture);
            }
        }
    }
}
