//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Resourses.Order {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Store.Resourses.Order.OrderStrings", typeof(OrderStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer .
        /// </summary>
        public static string CustomerID {
            get {
                return ResourceManager.GetString("CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select valid сustomer.
        /// </summary>
        public static string CustomerID_validation_error_message {
            get {
                return ResourceManager.GetString("CustomerID_validation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required date of supply.
        /// </summary>
        public static string RequiredDate {
            get {
                return ResourceManager.GetString("RequiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship address of supply.
        /// </summary>
        public static string ShipAddress {
            get {
                return ResourceManager.GetString("ShipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid ship address of supply.
        /// </summary>
        public static string ShipAddress_validation_error_message {
            get {
                return ResourceManager.GetString("ShipAddress_validation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ship city of supply.
        /// </summary>
        public static string ShipCity {
            get {
                return ResourceManager.GetString("ShipCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid ship city of supply.
        /// </summary>
        public static string ShipCity_validation_error_message {
            get {
                return ResourceManager.GetString("ShipCity_validation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship country of supply.
        /// </summary>
        public static string ShipCountry {
            get {
                return ResourceManager.GetString("ShipCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid ship country.
        /// </summary>
        public static string ShipCountry_validation_error_message {
            get {
                return ResourceManager.GetString("ShipCountry_validation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped date of supply.
        /// </summary>
        public static string ShippedDate {
            get {
                return ResourceManager.GetString("ShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship postal code of supply.
        /// </summary>
        public static string ShipPostalCode {
            get {
                return ResourceManager.GetString("ShipPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid ship postal code of supply.
        /// </summary>
        public static string ShipPostalCode_validation_error_message {
            get {
                return ResourceManager.GetString("ShipPostalCode_validation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipRegion of supply.
        /// </summary>
        public static string ShipRegion {
            get {
                return ResourceManager.GetString("ShipRegion", resourceCulture);
            }
        }
    }
}
